name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: numworks/setup-msys2@v1
    - run: |
      msys2do pacman -S mingw-w64-x86_64-gcc
      pacman -S mingw-w64-x86_64-make
      mingw32-make
