name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: numworks/setup-msys2@v1
    - run: |
        msys2do pacman -Sy mingw-w64-x86_64-gcc
        msys2do pacman -Sy make
        msys2do make
